title: Software Design | Spring 2020
short_title: Software Design
description: An introduction to software design.
timezone: America/New_York
calendar_url: ""
future: true

sections: 2
room_number: AC326, AC318

yandex_key: 0270fddbef1d3809

date_format: '%A %-m/%-d'
due_datetime_format: '%-I:%M %P, %a %-d %b'
due_date_format: '%a %b %-d'
part_due_date_format: '%a, %b %-d'

collections:
  activities:
    output: true
    layout: default
    title: Activities
  assignments:
    output: true
    layout: default
    title: Assignments
  notebooks:
    layout: default
    output: true
    permalink: /notes/:path
  toolboxes:
    layout: default
    output: false
    permalink: /toolboxes/:path

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: posts
    values:
      permalink: notes/:title
  - scope:
      path: ''
      type: assignments
    values:
      layout: assignment
  - scope:
      path: ''
      type: notebooks
    values:
      layout: notebook
      omit_title: true
  - scope:
      path: files
    values:
      layout: handout

plugins:
  - github-pages
  - jemoji
  - jekyll-redirect-from

kramdown:
  toc_levels: 2..6

livereload: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - config
  - notebooks
  - scripts
  - vendor
